spring.application.name=resilientapi
server.instance-id=${INSTANCE_ID:local}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
